INSERT INTO SHOP(BIZ_NUMBER, KAKAO_ID, PHONE_NUMBER, SHOP_NAME, SHOP_STATUS) VALUES('123-4567', 'kakao@kakao.com', '010-1111-1111', '헤어샵', 'NORMAL');
INSERT INTO EMPLOYEE(EMPLOYEE_STATUS, KAKAO_ID, NAME, PHONE_NUMBER, SHOP_ID) VALUES('NORMAL', 'employee1@kakao.com', '김직원', '010-2222-2222', NULL);
INSERT INTO EMPLOYEE(EMPLOYEE_STATUS, KAKAO_ID, NAME, PHONE_NUMBER, SHOP_ID) VALUES('NORMAL', 'employee2@kakao.com', '이직원', '010-3333-3333', 1);
